all:

	g++ -std=c++11 -pthread main.cpp lss.cpp lssconsole.cpp lssmanager.cpp lssnetworkhandler.cpp lssoperations.cpp ../structures/simplelist.cpp ../structures/node.cpp ../tokenizer.cpp ../../network/networkhandler/networkhandler.cpp ../../binaryoperations/baseconverter.cpp ../../binaryoperations/byteshandler.cpp ../../md5/md5.cpp -o main
