all:

	g++ -std=c++11 -pthread main.cpp lss.cpp lssconsole.cpp lssmanager.cpp lssnetworkhandler.cpp lssoperations.cpp ../structures/simplelist.cpp ../tokenizer.cpp ../../network/networkhandler/networkhandler.cpp -o main
